### ISSUE TITLE
DPL-1069 - As developers we need to introduce volume check to support volume tracking

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1200]
**User story**
As developers we need to introduce volume check to support volume tracking

**Who are the primary contacts for this story**
Steve / Ben

**Who is the nominated tester for UAT**
James / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] the input of a required volume and a source
- [x] the retrieval of the primary aliquot and derived aliquots for the source
- [x] the calculation of the used volume by the sum of the volumes of the derived aliqouts
- [x] the calculation of the available volume by subtracting the used volume from the original volume of the primary aliquot
- [x] a calculation of whether there is enough volume available by checking of the required volume is greater than the available volume
- [x] a failure response if there is insufficient volume available
- [x] a success response if there is sufficient volume available

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #1186
- #1136

**Additional context**
This would be best done as a separate library or an addition to aliquotable.

- Volume checking process map: [https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_l[…]3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679](https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_loc=116%2C-4472%2C6583%2C3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679)
- Multiplexing ERD: https://lucid.app/lucidchart/56eec268-2911-44c4-ab4b-87393e811738/edit?view_items=Fm2l5AbOONXb&invitationId=inv_81ba033e-8594-44c3-a37f-fd0c07fb4803
- Multiplexing process map: https://lucid.app/lucidchart/343de76c-d3e5-4a26-92c4-7bc10d919fb8/edit?page=0_0&invitationId=inv_13a8dd3b-ef1b-4f4e-b160-0dbf45a6031f#

**Comment by BenTopping** [comment]
Probably worth mentioning we will have legacy data we will want to ignore / bypass this.
Maybe add a conditional to volume check to ignore anything older than the date this is introduced.
