### ISSUE TITLE
DPL-1070 - As a long read user when I modify the library volume I would like a volume check performed to ensure the integrity of the data

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1201]
**User story**
As a long read user when I modify the library volume I would like a volume check performed to ensure the integrity of the data. We need to ensure that changing the original volume does not lead to a negative used volume or that if the volume used has exhausted the library we can modify the original volume accordingly.

**Who are the primary contacts for this story**
Steve / Ben / Seena

**Who is the nominated tester for UAT**
James / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] a check if the original library volume is changed
- [ ] rejection of the change if volume is changed to less than the current used volume
- [ ] acceptance of the change if the is changed to more the current used volume

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #1186
- #1136

**Additional context**
- Volume checking process map: [https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_l[…]3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679](https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_loc=116%2C-4472%2C6583%2C3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679)
- Multiplexing ERD: https://lucid.app/lucidchart/56eec268-2911-44c4-ab4b-87393e811738/edit?view_items=Fm2l5AbOONXb&invitationId=inv_81ba033e-8594-44c3-a37f-fd0c07fb4803
- Multiplexing process map: https://lucid.app/lucidchart/343de76c-d3e5-4a26-92c4-7bc10d919fb8/edit?page=0_0&invitationId=inv_13a8dd3b-ef1b-4f4e-b160-0dbf45a6031f#
