### ISSUE TITLE
DPL-1072 - As a long read user when I create a pool I want to perform a check to ensure that enough library volume is available to retain the integrity of the data

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1203]
**User story**
As a long read user when I create a pool I want to perform a check to ensure that enough library volume is available to retain the integrity of the data

**Who are the primary contacts for this story**
Steve / James / Ben / Seena

**Who is the nominated tester for UAT**
James / Long Read

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] checking that when a library is added to a pool that the volume is sufficient
- [ ] rejection of the change if the volume is not sufficient 
- [ ] acceptance of the change if there is enough volume

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #1186
- #1136

**Additional context**
