### ISSUE TITLE
Revio Multiplexing - Disassociating libraries from pools (phase 2)

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1222]
Stories:

- [x] #1214 
- [x] #1154 
- [x] sanger/traction-ui#1511
- [ ] sanger/traction-ui#1510
- [ ] sanger/traction-ui#1509
- [ ] #1194 
- [ ] sanger/traction-ui#1423

**Comment by stevieing** [comment]
Task list (stories):

- [ ] deploy traction-service and traction-ui to training
- [ ] check traction_service snapshot appears in training
- [ ] check whether training sends messages
- [ ] DPL-997 - library destroy
- [ ] DPL-997 - code review
- [ ] DPL-997 - merge into epic
- [ ] DPL-1064 - merge into epic
- [ ] DPL-1065 - library edit [WIP]
- [ ] final review
- [ ] create release

Task list - UAT:

- [ ] 

Task list - deploy to production:

- [ ]
