### ISSUE TITLE
Y24-059 - As developers we need to run a volume check on all existing production data to decide how to ensure there are no issues when we add the volume check to libraries

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1293]
**Description**
As developers we need to run a volume check on all existing production data to decide how to ensure there are no issues when we add the volume check to libraries

**Who the primary contacts are for this work**
Steve / James / Ben / Seena

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**

**Tasks:**

- [ ] create a production dump of the libraries data
- [ ] run a volume check against the data
- [ ] highlight areas which might cause data integrity issues
- [ ] discuss remediation with long read
