### ISSUE TITLE
Y24-096: Publish volume tracking message from Traction Service

### ISSUE THREAD

**Issue by dasunpubudumal** [sanger/traction-service#1322]
**User story**
As a developer, I need to setup a connection between Traction Service and the Enterprise Message Queue (EMQ) so that I can publish volume tracking messages into EMQ which are then consumed by ToL Lab Share. 

I need to use the exchange and queues that are already set up in https://github.com/sanger/General-Backlog-Items/issues/397 to set up a connection, and publish the aliquot creation message discussed in https://github.com/sanger/tol-lab-share/issues/57 to EMQ.

The schema for the message is defined in the story https://github.com/sanger/General-Backlog-Items/issues/396, and needs to be validated by fetching the schema from RedPanda schema store.

Note that stories https://github.com/sanger/traction-service/issues/1202 and https://github.com/sanger/traction-service/issues/1206 are focused on sending the messages from Traction. Therefore, the scope of this particular story is only confined to establishing the connection and sending a rough message into the EMQ. Within the scope of this story, I do not have to consider _when_ I need to send a volume tracking message. That will be implemented in  https://github.com/sanger/traction-service/issues/1202 and https://github.com/sanger/traction-service/issues/1206.

**Who are the primary contacts for this story**
Dasun, Stuart, Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Create a user account for traction in deployment project for EMQ
- [ ] To establish a connection between Traction Service and EMQ to publish messages into the EMQ.
- [ ] To publish an aliquot creation message using the Traction Service, you should design a generic method for creating messages using existing config files and then publish them
 This could be done using the Rails console, until stories https://github.com/sanger/traction-service/issues/1202 and https://github.com/sanger/traction-service/issues/1206 are done. 
**Dependencies**
This story is blocked by the following dependencies:
- https://github.com/sanger/General-Backlog-Items/issues/396
- https://github.com/sanger/General-Backlog-Items/issues/397

References
This story has a non-blocking relationship with:
- https://github.com/sanger/tol-lab-share/issues/57
- https://github.com/sanger/traction-service/issues/1202
- https://github.com/sanger/traction-service/issues/1206

**Additional context**

Diagrams: 

* [Messaging for Volume Tracking](https://lucid.app/lucidchart/6c8d5b09-4e57-4aba-a7ff-8d2cad161b3d/edit?viewport_loc=1140%2C-72%2C2053%2C977%2CUIRBfRVooFlW&invitationId=inv_9886517c-b0aa-4670-9e87-d820b8ddbba7)
* [Volume Tracking for Primary and Derived Aliquots](https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_loc=-282%2C-8109%2C6941%2C3848%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679)
