### ISSUE TITLE
As a user (James W) I would like there to be a volume check for PacBio pools.

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-service#1348]
**User story**
As a user (James W) I would like there to be a volume check for PacBio pools.

**Who are the primary contacts for this story**
James W, Ben T, Seena N

**Who is the nominated tester for UAT**
James W

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Expose available_volume and used_volume in the PacBio pools resource
- [ ] Validate available_volume when editing a pool, the same as libraries. This should be feature flagged.
- [ ] Validate used_volume when adding a pool to a run so it doesn't violate the volume, the same as libraries. This should be a separate feature flag.
- [ ] Check existing prod data doesn't violate the volume check (prod dump to local or use rails console on server)

**Additional context**
A lot of this work should be similar to the PacBio Libraries behaviour.
