### ISSUE TITLE
Y24-227 - [CLEAN-UP] PacBio Pool Volume Tracking

### ISSUE THREAD

**Issue by SHIV5T3R** [sanger/traction-service#1376]
**Describe the Housekeeping**
This is a clean-up story for adding volume tracking to PacBio pools ([Y24-153](https://github.com/sanger/traction-service/issues/1348)). The validation that happens when modifying the volume will happen if the feature flag is enabled.

This should ideally be cleaned up before deploying UI/service changes to production. 

**Related stories**
https://github.com/sanger/traction-ui/issues/1784
https://github.com/sanger/traction-ui/issues/1785

Removed?
- [ ] y24_153__enable_volume_check_pacbio_pool_on_update
- [ ] y24_155_pacbio_run_pool_volume_validation
- [ ] y24_154_enable_used_volume_display_pool_edit
