### ISSUE TITLE
Y24-370 - As Tree of Life we would like the sample data in the warehouse when a library is created so that we can track back to the original plate or tube barcode to make the top up process more efficient

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1451]
**User story**
As Tree of Life we would like the sample data in the warehouse when a library is created so that we can track back to the original plate or tube barcode to make the top up process more efficient.

**Who are the primary contacts for this story**
Ruth / Caroline / Steve

**Who is the nominated tester for UAT**
PSD / Caroline

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] When a library is created the sample should be pushed to the aliquot table
- [x] The sample used_by should be the library
- [x] The sample should have a source barcode which is the plate or tube barcode

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
